### ISSUE TITLE
Error filtering alerts on host

### ISSUE THREAD

**Issue by dn0** [erigones/ludolph-zabbix#7]
Command: `alerts host 10` fails with exception:

```
Traceback (most recent call last):
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/ludolph/command.py", line 253, in wrap
    response = fun(obj, msg, *args, **kwargs)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/ludolph_zabbix/zapi.py", line 463, in alerts
    display_items=items, hosts_or_groups=args)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/ludolph_zabbix/zapi.py", line 332, in _show_alerts
    events = self._get_alert_events(triggers, since=since, until=until)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/ludolph_zabbix/zapi.py", line 263, in _get_alert_events
    missing_eventids = [t['lastEvent']['eventid'] for t in triggers if t['triggerid'] not in events]
TypeError: list indices must be integers, not str
```

**Comment by secult** [comment]
The issue is that an empty lastEvent object is not {} but []

**Comment by dn0** [comment]
@secult OK, so just update the if-clause in the list comprehension.
Also please check the code for more assumptions of non-empty `lastEvent`.
